# Generated by Django 3.0.2 on 2020-01-17 05:06

from django.db import migrations, models
import point_of_sale.api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, validators=[point_of_sale.api.validators.validate_phone_number]),
        ),
    ]
